services:
  server:
    container_name: server
    build: ""
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
    - ../db:/data/db:rw
    ports:
    - "27017:27017"